FROM python:3.9-slim AS build
WORKDIR /app
COPY app.py app.py
RUN pip install flask 
EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["app.py"]

FROM python:3.9-slim 
WORKDIR /app
COPY --from=build /app .
RUN pip install flask 
EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["app.py"]