apiVersion: v1 
kind: ReplicationController
metadata: 
  name: anilrc
spec: 
  replicas: 3
  selector: 
     app: nginx
  template: 
    metadata:
       labels:
          app: nginx
          env: dev
    spec: 
     containers: 
      - name: nginxth
        image: nginx        
