apiVersion: apps/v1
kind: Deployment
metadata:
  name: backdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-cntr
        image: hashicorp/http-echo
        args:
        - "-text=Hello from Backend"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 5678
  selector:
       app: backend